// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNEQ802InOMPzyEY84UyiC7fPdNrOU7F8',
    appId: '1:534595488726:web:021cc2329fa4d8c99e7277',
    messagingSenderId: '534595488726',
    projectId: 'healthmate-6fc75',
    authDomain: 'healthmate-6fc75.firebaseapp.com',
    storageBucket: 'healthmate-6fc75.appspot.com',
    measurementId: 'G-S6RSBT8F1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD6MBC_TkLwIShZzWbCS16EhBcT02H0Ew',
    appId: '1:534595488726:android:4c6759ce07e765fd9e7277',
    messagingSenderId: '534595488726',
    projectId: 'healthmate-6fc75',
    storageBucket: 'healthmate-6fc75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ8GHrCNKAgtB7ueOEW2935LFDTd9aOBQ',
    appId: '1:534595488726:ios:866a719e6fdc9ba99e7277',
    messagingSenderId: '534595488726',
    projectId: 'healthmate-6fc75',
    storageBucket: 'healthmate-6fc75.appspot.com',
    iosBundleId: 'com.example.healthmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ8GHrCNKAgtB7ueOEW2935LFDTd9aOBQ',
    appId: '1:534595488726:ios:866a719e6fdc9ba99e7277',
    messagingSenderId: '534595488726',
    projectId: 'healthmate-6fc75',
    storageBucket: 'healthmate-6fc75.appspot.com',
    iosBundleId: 'com.example.healthmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNEQ802InOMPzyEY84UyiC7fPdNrOU7F8',
    appId: '1:534595488726:web:3dea01f36a4a9a779e7277',
    messagingSenderId: '534595488726',
    projectId: 'healthmate-6fc75',
    authDomain: 'healthmate-6fc75.firebaseapp.com',
    storageBucket: 'healthmate-6fc75.appspot.com',
    measurementId: 'G-G96J9S0VFY',
  );
}
